crudsimple/urls.py
from django.contrib import admin
from django.urls import path
from simplecrud import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.tampildata),
    path('inputdata/',views.inputdata),
    path('simpandata',views.simpandata),
    path('hapusdata/<int:id>',views.hapusdata),
    path('editdata/<int:id>',views.editdata),
    path('updatedata/<int:id>',views.updatedata)    
]

simplecrud/models.py
from django.db import models

class Crudsimple(models.Model):
    id = models.IntegerField()
    id = models.AutoField(primary_key=True)
    nama = models.CharField(max_length=50)
    nim = models.IntegerField()
    fakultas = models.CharField(max_length=50)
    jurusan = models.CharField(max_length=50)

    class Meta:
        db_table = "simplecrud"

simplecrud/forms.py
from django import forms

from simplecrud.models import Crudsimple

class CrudsimpleForm(forms.ModelForm):
    class Meta:
        model = Crudsimple
        fields = "__all__"

simplecrud/views.py
from django.shortcuts import render,redirect
from simplecrud.forms import CrudsimpleForm
from simplecrud.models import Crudsimple

def tampildata(request):        
    return render(request,"index.html",{'tampilkandata':Crudsimple.objects.all()})

def inputdata(request):
    return render(request, "inputdata.html")

def simpandata(request):
    if request.method == "POST":
        form = CrudsimpleForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/') #Lihat Pada urls.py saat ingin men-redirect setelah aksi save.
            except:
                pass
    else:
        form = CrudsimpleForm()
    return render(request,'inputdata.html',{'form':form})

def hapusdata(request, id):
    Crudsimple.objects.get(id=id).delete()
    return redirect('/')

def editdata(request, id):
    return render(request, "editdata.html", {'editdatanya':Crudsimple.objects.get(id=id)})

def updatedata(request, id):
    formupdatedata = CrudsimpleForm(request.POST, instance=Crudsimple.objects.get(id=id))
    if formupdatedata.is_valid():
        formupdatedata.save()
        return redirect('/')
    return render(request,'editdata.html',{'updatedatanya':Crudsimple.objecs.get(id=id)})

simplecrud/templates/editdata.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  {% load static %}
  <title>CRUD Simpel menggunakan Django</title>
  <link href="{% static 'fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
</head>

<body>

  <div class="container">
    <h4 class="mt-4">CRUD Simpel menggunakan Django</h4>
    <p class="mb-4">Aplikasi Create, Read, Update, Delete Menggunakan Django Framework</p>
    <form method="POST" action="/updatedata/{{ editdatanya.id }}">
      {% csrf_token %}
      <div class="card shadow-sm mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Edit Data Mahasiswa Universitas X</h6>
        </div>
        <div class="card-body">
          <label>Nama Mahasiswa</label>
          <div class="form-group">
            <input type="text" class="form-control form-control-user" placeholder="Masukkan Nama Mahasiswa" name="nama"
              id="id_nama" value="{{ editdatanya.nama }}">
          </div>
          <label>Nim Mahasiswa</label>
          <div class="form-group">
            <input type="text" class="form-control form-control-user" placeholder="Masukkan NIM Mahasiswa" name="nim"
              id="id_nim" value="{{ editdatanya.nim }}" maxlength="11">
          </div>
          <label>Fakultas</label>
          <div class="form-group">
            <input type="text" class="form-control form-control-user" placeholder="Masukkan Asal Fakultas Mahasiswa"
              name="fakultas" id="id_fakultas" value="{{ editdatanya.fakultas }}">
          </div>
          <label>Jurusan</label>
          <div class="form-group">
            <input type="text" class="form-control form-control-user" placeholder="Masukkan Asal Jurusan Mahasiswa"
              name="jurusan" id="id_jurusan" value="{{ editdatanya.jurusan }}">
          </div>
        </div>
        <div class="card-footer">
          <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Simpan Data</button>
          <a href="/" class="btn btn-default">Batal</a>
        </div>
      </div>
    </form>
    <footer class="mt-5 mb-3">
      <div class="container my-auto">
        <div class="text-center my-auto">
          <span>developed by <a href="https://indrijunanda.gitlab.io" target="_blank" style="color: #424242;"><b>indrijunanda</b><a></span>
        </div>
      </div>
    </footer> 
  </div>

  <script src="{% static 'jquery/jquery.slim.min.js' %}"></script>
  <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

simplecrud/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  {% load static %}
  <title>CRUD Simpel menggunakan Django</title>
  <link href="{% static 'fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'datatable/datatables.min.css' %}" rel="stylesheet">

</head>

<body>
  <div class="container">
    <h4 class="mt-4">CRUD Simpel menggunakan Django</h4>
    <p class="mb-4">Aplikasi Create, Read, Update, Delete Menggunakan Django Framework</p>
    <a href="inputdata/" class="btn btn-primary mb-2"><i class="fas fa-upload"></i> Tambah Data Mahasiswa</a>
    <div class="card shadow-sm mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Data Mahasiswa Universitas X</h6>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th style="width: 20px">No.</th>
                <th>Nama</th>
                <th>NIM</th>
                <th>Fakultas</th>
                <th>Jurusan</th>
                <th style="width: 70px;">Aksi</th>
              </tr>
            </thead>
            <tbody>
              {% for tampilkandatanya in tampilkandata %}
              <tr>
                <td style="text-align: center">{{ forloop.counter }}</td>
                <td>{{ tampilkandatanya.nama }}</td>
                <td>{{ tampilkandatanya.nim }}</td>
                <td>{{ tampilkandatanya.fakultas }}</td>
                <td>{{ tampilkandatanya.jurusan }}</td>
                <td style="text-align: center">
                  <a href="/editdata/{{ tampilkandatanya.id }}" class="btn btn-primary btn-sm" title="Edit"><i
                    class="fas fa-edit"></i></a>
                  <a href="/hapusdata/{{ tampilkandatanya.id }}" class="btn btn-danger btn-sm" title="Hapus"><i
                      class="fas fa-trash"></i></a>                  
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <footer class="mt-5 mb-3">
      <div class="container my-auto">
        <div class="text-center my-auto">
          <span>developed by <a href="https://indrijunanda.gitlab.io" target="_blank" style="color: #424242;"><b>indrijunanda</b><a></span>
        </div>
      </div>
    </footer> 
  </div>
 <script src="{% static 'jquery/jquery.slim.min.js' %}"></script>
 <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
 <script src="{% static 'datatable/datatables.min.js' %}"></script> 
 <script>
   $(document).ready(function () {
     $('#dataTable').DataTable();
   });
 </script>

</body>

</html>

simplecrud/templates/inputdata.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  {% load static %}
  <title>CRUD Simpel menggunakan Django</title>
  <link href="{% static 'fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">  
</head>

<body>
  <div class="container">
    <h4 class="mt-4">CRUD Simpel menggunakan Django</h4>
    <p class="mb-4">Aplikasi Create, Read, Update, Delete Menggunakan Django Framework</p>
    <form method="POST" action="/simpandata">
      {% csrf_token %}
      <div class="card shadow-sm mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Input Data Mahasiswa Universitas X</h6>
        </div>
        <div class="card-body">
          <label>Nama Mahasiswa</label>
          <div class="form-group">
            <input type="text" class="form-control form-control-user" placeholder="Masukkan Nama Mahasiswa" name="nama"
              id="id_nama">
          </div>
          <label>Nim Mahasiswa</label>
          <div class="form-group">
            <input type="text" class="form-control form-control-user" placeholder="Masukkan NIM Mahasiswa" name="nim"
              id="id_nim" maxlength="11">
          </div>
          <label>Fakultas</label>
          <div class="form-group">
            <input type="text" class="form-control form-control-user" placeholder="Masukkan Asal Fakultas Mahasiswa"
              name="fakultas" id="id_fakultas">
          </div>
          <label>Jurusan</label>
          <div class="form-group">
            <input type="text" class="form-control form-control-user" placeholder="Masukkan Asal Jurusan Mahasiswa"
              name="jurusan" id="id_jurusan">
          </div>
        </div>
        <div class="card-footer">
          <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Simpan Data</button>
          <a href="/" class="btn btn-default">Batal</a>
        </div>
      </div>
    </form>
    <footer class="mt-5 mb-3">
      <div class="container my-auto">
        <div class="text-center my-auto">
          <span>developed by <a href="https://indrijunanda.gitlab.io" target="_blank" style="color: #424242;"><b>indrijunanda</b><a></span>
        </div>
      </div>
    </footer> 
  </div>

  <script src="{% static 'jquery/jquery.slim.min.js' %}"></script>
  <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>